eMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front-end.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from accounts.constants.constants import *
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings

from django.contrib.auth import get_user_model


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):

    user_type = (
        ('customer', 'customer'),
        ('professionnal', 'professionnal'),
    )

    username = None
    email = models.EmailField(max_length=30, unique=True)
    role = models.CharField(choices=user_type, max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = [] # needed later when wanna monetize it

    objects = UserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    pass


class Post(models.Model):

    name = models.CharField(max_length=100) #titre du produit
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    price = models.FloatField(default=None)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=10000)
    category = models.CharField(choices=CATEGORIES, max_length=80, blank=True, null=True)
    type_immobilier = models.CharField(choices=TYPES_IMMOBILIER, max_length=50, blank=True, null=True)
    type_automobile = models.CharField(choices=TYPES_AUTOMOBILE, max_length=50, blank=True, null=True)
    area = models.CharField(max_length=60)
    city = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    images = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.post.name


class PhoneNumber(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.IntegerField(unique=True)


class UserSearch(models.Model):
    word_entered = models.CharField(max_length=100)
    category = models.CharField(choices=CATEGORIES, max_length=80, blank=True, null=True)
    search_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.word_entered


class AddToFavorite(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    current_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post

templates/forms/login.html
{% extends "base.html" %}
{% load static %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}">

{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-6 mt-5">
            <h3>Bonjour </h3>
            <p>Connectez-vous pour bénéficier nos produits</p>
            <form method="POST">
                {% csrf_token %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %}class="alert alert-danger"{% endif %}>
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <p><input type="text" name="username" placeholder="Email" class="form-control" required></p>
                <p><input type="password" name="password" placeholder="Mot de passe" class="form-control" required></p>
                <input type="submit" class="btn btn-primary">
                <p>Vous n'avez pas de compte? Clikez <a href="compte">ici</a> </p>
                <p>Vous avez oublié votre mot de passe, cliquez <a href="password_reset">ici</a></p>
            </form>
        </div>

</div>
{% endblock %}

templates/forms/multi-images.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
     <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="images" multiple>
        <button>Upload</button>
    </form>
    <hr>
    {% for img in images %}
    <img src="{{ img.images.url }}" alt="Image">
    {% endfor %}
{% endblock %}

templates/forms/post.html
{% extends 'base.html' %}
{% load static %}

{% block js_content %}
<script src="{% static 'js/post/post_handler.js' %}"></script>
<script src="{% static 'js/post/selectChange.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4 mt-5">
            <h4 class="mt-5">Créez votre annonce</h4>
            <form action="" method="POST" class="mt-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ post.as_p }}
                    {{ imageform.as_p }}
                <input type="submit" class="btn btn-success">
            </form>
        </div>
    </div>

   <!-- <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form method="'POST" class="mt-5" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="id_name">Titre:</label>
                <input type="text" name="name" name="post" class="form-control" placeholder="Titre de votre annonce"
                       required class="form-control-sm pr-4" style="width:100%" id="id_name">

                <label for="id_price">Prix:</label>
                <input type="text" name="price" name="post" class="form-control"
                       required class="form-control-sm pr-4" style="width:100%" id="id_price">

                <label for="id_area">Quartier:</label>
                <input type="text" name="price" name="post" class="form-control"
                       required class="form-control-sm pr-4" style="width:100%" id="id_area">

                    <label for="id_city">Ville:</label>
                    <input type="text" name="city" name="city" class="form-control"
                           style="width:100%" required id="id_city"></p>

                <p>
                    <label for="id_category">Categorie:</label>
                        <select name="category" id="id_category" class="form-control">
                          <option value="Autre">Autre</option>
                          <option value="Immobilier">Immobilier</option>
                          <option value="Automobile">Automobile</option>
                          <option value="Alimentation">Alimentation</option>
                          <option value="Electroniques">Electroniques</option>
                        </select>
                </p>

                     <label for="id_type_automobile">Type automobile:</label>
                        <select name="type_automobile" id="id_type_automobile" class="form-control">
                            <option value="Neuf">Neuf</option>
                            <option value="Occassion">Ocassion</option>
                            <option value="Ancien">Ancien</option>
                        </select></p>
                <p>
                      <label for="id_type_immobilier">Type immobilier:</label>
                        <select name="type_immobilier" id="id_type_immobilier" class="form-control">
                          <option value="Maison">Maison</option>
                          <option value="Appartement">Appartement</option>
                          <option value="Location">Location</option>
                          <option value="Bureaux">Bureaux</option>
                    </select></p>
                <p>
                    <label for="description">Description:</label>
                    <textarea id="description" class="form-control" style="width:100%;"></textarea>
                </p>

                <input type="submit" class="btn btn-success" value="Poster">

            </form>
        </div>
    </div>
    -->
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>

{% endblock %}

templates/forms/signup.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type='text/css' href="{% static 'css/global.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="form_signup mx-5 my-5">
                <h3 class="mb-1 mt-5 mb-5">Création de compte </h3>
                <form method="POST">
                    {% csrf_token %}

                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                    {{ message}}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {{ userform.as_p }}
                    {{ form.as_p }}

                    <input type="submit" class="btn btn-primary mb-3" value="soumettre">
                    <p> Vous avez deja de compte? Clikez <a href="connexion">ici</a></p>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="avatar mt-5 mr-5">
                <img src="{% static 'images/avatar.jpg' %}">
            </div>
        </div>

    </div>
</div>

{% endblock %}