eMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front-end.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from accounts.constants.constants import *
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings

from django.contrib.auth import get_user_model


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):

    user_type = (
        ('customer', 'customer'),
        ('professionnal', 'professionnal'),
    )

    username = None
    email = models.EmailField(max_length=30, unique=True)
    role = models.CharField(choices=user_type, max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = [] # needed later when wanna monetize it

    objects = UserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    pass


class Post(models.Model):

    name = models.CharField(max_length=100) #titre du produit
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    price = models.FloatField(default=None)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=10000)
    category = models.CharField(choices=CATEGORIES, max_length=80, blank=True, null=True)
    type_immobilier = models.CharField(choices=TYPES_IMMOBILIER, max_length=50, blank=True, null=True)
    type_automobile = models.CharField(choices=TYPES_AUTOMOBILE, max_length=50, blank=True, null=True)
    area = models.CharField(max_length=60)
    city = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    images = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.post.name


class PhoneNumber(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.IntegerField(unique=True)


class UserSearch(models.Model):
    word_entered = models.CharField(max_length=100)
    category = models.CharField(choices=CATEGORIES, max_length=80, blank=True, null=True)
    search_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.word_entered


class AddToFavorite(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    current_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>E-Market</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
     <script src="{% static 'js/jquery.js' %}"></script>
     <script src="{% static 'js/bootstrap.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <link rel="stylesheet" type='text/css' href="{% static 'css/home.css' %}">
      {% block css_content %} {% endblock %}
  </head>
  <body>
  {% include 'navbar.html' %}
    {% block content %}{% endblock %}
  {% block js_content %}{% endblock %}

  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type='text/css' href="{% static 'css/home.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'css/global.css' %}">
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">

        <div class="mx-5 col-12 col-md-8 mt-5">
            <h2>Plus de 100 annonces par jour sur Carrefour Hanana</h2>
            <div class="shadow p-3 mb-5 bg-white rounded announcement">

                <form method="POST" class="mt-5">
                    {% csrf_token %}
                    <input type="text" class="form-control mb-3" name="word"
                           placeholder="Votre Recherche" required>

                    <select name="category" id="category-select" class="form-control">
                    <option value="">Choissisez votre categorie</option>
                    <option value="Automobile">Automobile</option>
                    <option value="Immobilier">Immobilier</option>
                    <option value="Electronique">Electronique</option>
                    <option value="Alimentation">Alimentation</option>
                    <option value="Autre">Autre</option>
                </select>

                    <input type="submit" class="btn btn-primary mt-3" value="Rechercher">
                </form>
            </div>

        </div>
        <div class="col-md-4 mt-5 mx-5">
            <h3 class=" mb-3 introduction">Achetez, Vendez les biens que vous desirez!
                Nous avons tous en stock pour vous.</h3>
            <p>Si vous avez à vendre ou si vous recherchiez de quoi acheter, vous êtes au bon endroit. </p>

            <div class="chat">
                <a href="create-post" class="btn btn-lg btn-success mb-2">Deposer votre annonce</a>
                <a href="compte" class="btn btn-lg btn-primary mb-2">Créer de compte</a>
            </div>
        </div>
        <div class="col-md-4 mt-5">
            <img src="{% static 'images/stock_1.jpg' %}" style="width:100%" class="image_stocks"
                 alt="vente en ligne voiture maison immobilier tchad">
        </div>

    </div>

</div>

{% endblock %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-secondary">
  <a class="navbar-brand" href="{% url 'home' %}">Carrefour-Hanana</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon" style="color: white !important;"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'home' %}">Accueil <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'all_posts' %}">Nos annonces</a>
      <a class="nav-item nav-link active" href="{% url 'login' %}">Connectez-vous</a>
    </div>
  </div>
</nav>

templates/post.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
       <div class="row">
           {% for post in posts %}
                <div class="col-md-4 mt-5">
                    <div class="card" style="width: 18rem;">
                      <img class="card-img-top" src="{{ post.image_set.all.0.images.url }}"  height="100%"
                          width="100%" alt="tchad, vente de produits en ligne">
                      <div class="card-body">
                        <h5 class="card-title">{{ post.name }}</h5>
                        <h5 class="card-title">{{ post.price }} Francs</h5>
                        <a href="{% url 'single_post' post.id %}" class="btn btn-primary">Detail</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
       </div>
    </div>

{% endblock %}